info:
  app:
    name: "@project.name@"
    version: "@project.version@"

server.port: 8095

spring:
  application:
    name: scalable-crud-app
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      enabled: true
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
